name: CI Build Setup
description: Sets up build dependencies

runs:
  using: composite
  steps:
    - id: python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - id: apt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          check \
          scdoc \ 
          build-essential \
          check \
          meson \
          ninja-build \
          binutils \
          ccache \
          dbus-x11 \
          doxygen \
          gettext \
          imagemagick \
          libbrotli-dev \
          libasound2-dev \
          libavahi-client-dev \
          libblkid-dev \
          libbluetooth-dev \
          libbullet-dev \
          libc6-dev \
          libcogl-dev \
          libcurl4-openssl-dev \
          libdbus-1-dev \
          libfontconfig1-dev \
          libfreetype6-dev \
          libfribidi-dev \
          libgif-dev \
          libgl1-mesa-dev \
          libglib2.0-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          libharfbuzz-dev \
          libibus-1.0-dev \
          libiconv-hook-dev \
          libjpeg-dev \
          libjpeg-turbo8-dev \
          luajit \
          libluajit-5.1-dev \
          liblua5.2-dev \
          liblz4-dev \
          libmount-dev \
          libopenjp2-7-dev \
          libpam0g-dev \
          libpcre3-dev \
          libpng-dev \
          libpoppler-cpp-dev \
          libpoppler-dev \
          libpoppler-private-dev \
          libproxy-dev \
          libpulse-dev \
          libraw-dev \
          librsvg2-dev \
          libscim-dev \
          libsndfile1-dev \
          libspectre-dev \
          libssl-dev \
          libsystemd-dev \
          libtiff5-dev \
          libtool \
          libudev-dev \
          libunwind-dev \
          libudisks2-dev \
          libunibreak-dev \
          libwebp-dev \
          libxcb-keysyms1-dev \
          libx11-dev \
          libxcomposite-dev \
          libxcursor-dev \
          libxdamage-dev \
          libxext-dev \
          libxinerama-dev \
          libxkbfile-dev \
          libxrandr-dev \
          libxrender-dev \
          libxss-dev \
          libxtst-dev \
          linux-tools-common \
          python3-pip \
          python3-setuptools \
          systemd \
          libxpresent-dev \
          libsdl2-dev \
          cmake \
          libinput-dev \
          libheif-dev \
          librlottie-dev \
          libxkbcommon-x11-dev \
          valgrind \
          libvncserver-dev \
          libexif-dev \
          xwayland \
          libhyphen-dev \
          libavif-dev \
          libhwy-dev
      shell: bash
    # - id: doxy
    #   run: git clone https://github.com/davatorium/doxy-coverage
    #   shell: bash
    # - id: check
    #   run: |
    #     curl -L https://github.com/libcheck/check/releases/download/0.14.0/check-0.14.0.tar.gz | tar xzf -
    #     cd check-0.14.0
    #     ./configure
    #     make
    #     sudo make install
    #     sudo ldconfig
    #   shell: bash
