---

name: Gather Pull Request Metadata

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gather-metadata:
    if: github.repository == 'dimmus/efl'
    runs-on: ubuntu-22.04

    steps:
      - name: Repository checkout
        uses: actions/checkout@b80ff79f1755d06ba70441c368a6fe801f5f3a62

      - id: metadata
        name: Gather Pull Request Metadata
        uses: redhat-plumbers-in-action/gather-pull-request-metadata@17821d3bc27c1efed339595898c2e622accc5a1b

      - name: Upload Pull Request Metadata artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        with:
          name: Pull Request Metadata
          path: ${{ steps.metadata.outputs.metadata-file }}
          retention-days: 1
