---

name: Gather Pull Request Metadata

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gather-metadata:
    if: github.repository == 'dimmus/efl'
    runs-on: ubuntu-22.04

    steps:
      - name: Repository checkout
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98

      - id: metadata
        name: Gather Pull Request Metadata
        uses: redhat-plumbers-in-action/gather-pull-request-metadata@62fc85c7acd15db62a0bdf007c8dbeda86eaf3b6

      - name: Upload Pull Request Metadata artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: Pull Request Metadata
          path: ${{ steps.metadata.outputs.metadata-file }}
          retention-days: 1
